name: Doctors Service CI/CD PipeLine

on:
  pull_request:
    paths:
      - 'doctors/**'
  push:
    branches:
      - main
    paths:
      - 'doctors/**'


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t farquleet/doctors-service:${{ github.sha }} ./doctors
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push farquleet/doctors-service:${{ github.sha }}
