name: Frontend Service CI/CD PipeLine

on:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t farquleet/frontend-service:${{ github.sha }} ./frontend
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push farquleet/frontend-service:${{ github.sha }}
